In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor


In [ ]:
dataframe=pd.read_csv('/content/sample_data/MalnutritionData.csv')
dataset=dataframe.values
print(dataset)

[[  9.4  10.4  11.4  12.4  13.4  11.4]
 [ 10.4  11.4  12.4  13.4  14.4  12.4]
 [ 11.4  12.4  13.4  14.4  15.4  13.4]
 [ 12.4  13.4  14.4  15.4  16.4  14.4]
 [ 13.4  14.4  15.4  16.4  17.4  15.4]
 [ 14.4  15.4  16.4  17.4  18.4  16.4]
 [ 15.4  16.4  17.4  18.4  19.4  17.4]
 [ 16.4  17.4  18.4  19.4  20.4  18.4]
 [ 17.4  18.4  19.4  20.4  21.4  19.4]
 [ 18.4  19.4  20.4  21.4  22.4  20.4]
 [ 19.4  20.4  21.4  22.4  23.4  21.4]
 [ 20.4  21.4  22.4  23.4  24.4  22.4]
 [ 21.4  22.4  23.4  24.4  25.4  23.4]
 [ 22.4  23.4  24.4  25.4  26.4  24.4]
 [ 23.4  24.4  25.4  26.4  27.4  25.4]
 [ 24.4  25.4  26.4  27.4  28.4  26.4]
 [ 25.4  26.4  27.4  28.4  29.4  27.4]
 [ 26.4  27.4  28.4  29.4  30.4  28.4]
 [ 27.4  28.4  29.4  30.4  31.4  29.4]
 [ 28.4  29.4  30.4  31.4  32.4  30.4]
 [ 29.4  30.4  31.4  32.4  33.4  31.4]
 [ 30.4  31.4  32.4  33.4  34.4  32.4]
 [ 31.4  32.4  33.4  34.4  35.4  33.4]
 [ 32.4  33.4  34.4  35.4  36.4  34.4]
 [ 33.4  34.4  35.4  36.4  37.4  35.4]
 [ 34.4  35.4  36.4  37.4

In [ ]:
x=dataset[:,0:5]
print(x.shape)
y=dataset[:,-1]
y=np.reshape(y,(-1,1))
print(y.shape)


(100, 5)
(100, 1)


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [ ]:
model=Sequential()
model.add(Dense(12,input_dim=5,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='linear'))
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                72        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 185
Trainable params: 185
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='mse', optimizer='adam', metrics=['mse','mae'])

In [ ]:
history=model.fit(x_train,y_train,epochs=150,batch_size=20)

Epoch 1/150
4/4 [==============================] - 1s 4ms/step - loss: 11304.2959 - mse: 11304.2959 - mae: 97.3936
Epoch 2/150
4/4 [==============================] - 0s 4ms/step - loss: 9839.0000 - mse: 9839.0000 - mae: 90.7331
Epoch 3/150
4/4 [==============================] - 0s 6ms/step - loss: 8527.0029 - mse: 8527.0029 - mae: 84.5149
Epoch 4/150
4/4 [==============================] - 0s 5ms/step - loss: 7315.5127 - mse: 7315.5127 - mae: 78.4351
Epoch 5/150
4/4 [==============================] - 0s 4ms/step - loss: 6307.3760 - mse: 6307.3765 - mae: 72.7580
Epoch 6/150
4/4 [==============================] - 0s 4ms/step - loss: 5418.5522 - mse: 5418.5522 - mae: 67.2863
Epoch 7/150
4/4 [==============================] - 0s 5ms/step - loss: 4533.6260 - mse: 4533.6260 - mae: 61.6789
Epoch 8/150
4/4 [==============================] - 0s 4ms/step - loss: 3786.0193 - mse: 3786.0193 - mae: 56.3460
Epoch 9/150
4/4 [==============================] - 0s 6ms/step - loss: 3121.9241 - mse: 3121.9

In [ ]:
xnew=np.array([[9.4,10.1,10.3,10.4,10.6]])
ynew=model.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0],ynew[0]))

X=[ 9.4 10.1 10.3 10.4 10.6], Predicted=[10.328464]


In [ ]:
model.save('/content/predtest.h5')

In [ ]:
from tensorflow.python import keras
import tensorflow

modelnew = keras.models.load_model('/content/predtest.h5')
converter=tensorflow.lite.TFLiteConverter.from_keras_model(modelnew)
tflite_model = converter.convert()
open("predmodel.tflite","wb").write(tflite_model)

2620

In [ ]:
xnew=np.array([[9.4,10.1,10.3,10.4,10.6]])
ynew=model.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0],ynew[0]))

X=[ 9.4 10.1 10.3 10.4 10.6], Predicted=[10.328464]
